### ISSUE TITLE
Missing required environment variable NEXT_PUBLIC_DEPLOYMENT_URL

### ISSUE THREAD

**Issue by rozenmd** [joelhooks/next-typescript-tailwind-mdx-starter#1]
Hey Joel,

Just spun this up to check it out, looks like `yarn dev` is expecting an `.env` file with `NEXT_PUBLIC_DEPLOYMENT_URL` set:

```
yarn run v1.17.3
$ next dev
❌  Missing required environment variable NEXT_PUBLIC_DEPLOYMENT_URL
{ Error: Some required environment variables are missing: NEXT_PUBLIC_DEPLOYMENT_URL
    at checkEnv (/Volumes/External SSD/MacMiniExternal/Projects/next-typescript-tailwind-mdx-starter/node_modules/@47ng/check-env/dist/index.js:67:15)
    at Object.<anonymous> (/Volumes/External SSD/MacMiniExternal/Projects/next-typescript-tailwind-mdx-starter/next.config.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at loadConfig (/Volumes/External SSD/MacMiniExternal/Projects/next-typescript-tailwind-mdx-starter/node_modules/next/dist/next-server/server/config.js:6:116) missing: [ 'NEXT_PUBLIC_DEPLOYMENT_URL' ] }
error Command failed with exit code 1.
```

Happy to make a PR to fix if that's cool

**Comment by joelhooks** [comment]
this would mostly be a documentation issue, but I actually removed this today :)
